// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// SigninRequest defines model for SigninRequest.
type SigninRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SigninResponse defines model for SigninResponse.
type SigninResponse struct {
	// Token JWT authentication token
	Token *string `json:"token,omitempty"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignupResponse defines model for SignupResponse.
type SignupResponse struct {
	Email *string  `json:"email,omitempty"`
	Id    *float32 `json:"id,omitempty"`
}

// SigninJSONRequestBody defines body for Signin for application/json ContentType.
type SigninJSONRequestBody = SigninRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest
