openapi: 3.0.0
info:
  title: Chat Server API
  version: 1.0.0
  description: API for the Chat Server application

# servers:
#   - url: http://localhost:8080
    # description: Local development server

paths:
  /auth/signup:
    post:
      summary: Register a new user
      description: Creates a new user account in the system
      operationId: signup
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
components:
  schemas:
    SignupRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 8
      required:
        - email
        - password

    SignupResponse:
      type: object
      properties:
        id:
          type: number
          example: 1
        email:
          type: string
          example: "abc@email.com"

        # '400':
        #   description: Invalid request parameters
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: string
        #             example: "Invalid email or password"
        # '409':
        #   description: User already exists
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: string
        #             example: "User with this email already exists"
        # '500':
        #   description: Internal server error
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
                  # error:
                  #   type: string
                  #   example: "Internal server error"
